### ISSUE TITLE
Continuous integration / automated testing

### ISSUE THREAD

**Issue by agausmann** [strongback/strongback-java#5]
I am setting up a Jenkins CI server for my personal projects. Addition is painless since Jenkins supports Ant build scripts, and I think it would be a very useful tool for automated testing and release management.

The only downside is that the server has to authenticate as a user with admin rights in order to publish build statuses on GitHub. That means an existing owner/collaborator will have to generate an access token, or I will have to be promoted since I already have a token installed.

**Comment by rhauch** [comment]
+1 for automated CI -- it is a must have.

But IMO we don't want to rely upon the resources of any individual. Instead, I think we should use https://travis-ci.org, which is cloud-based, free for open source communities, far easier to configure than Jenkins, and works really well with GitHub. For example, it will annotate our GitHub repository with flags that state whether it builds successfully, and we can even add hooks so that any PRs are automatically built after the PR is created _before_ someone has to look at it. And it already knows about Ant, and [by default](http://docs.travis-ci.com/user/languages/java/#sts=Projects%20Using%20Ant) it will run `ant test` (tho we can [change that](http://docs.travis-ci.com/user/languages/java/#sts=Projects%20Using%20Ant) if we need to).

The only reason I didn't register our repository already was that we need a build script, so as soon as issue #4 is resolved we can add Strongback to Travis to get automatic CI.

**Comment by agausmann** [comment]
Good idea. I don't have experience in Travis, but it seems it can do everything I was planning on doing. I agree; let's set it up once we have a build system.
